name: Cypress test
on: 
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request: 
    types: [opened, edited, reopened]

jobs:
  cypress_run:
    runs-on: ubuntu-latest
    steps: 
      - name: Get project files
        uses: actions/checkout@v4
      - name: Install all dependencies
        run: npm install --force
      - name: Run tests
        run: npm run cy:run:server
      - name: Create report
        run: npm run report:all
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: merged-report/
      